site_name: Unicornia - Wiki
site_url: https://wiki.unicornia.net/
site_author: Unicornia - Kirin
site_description: >-
  The Best and Friendliest Online LGBTQ+ Community on Discord and Everywhere else. 
  Join our huge online community of like-minded people today!

# Repository
repo_name: kirin-3/unicornia-wiki
repo_url: https://github.com/kirin-3/unicornia-wiki

# Copyright
copyright: Copyright &copy; 2020 - 2022 Unicornia

# Configuration
theme:
  name: null
  logo: assets/logo.svg
  custom_dir: !ENV [THEME_DIR, "material"]

  # Static files
  static_templates:
    - 404.html

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  features:
    - content.code.annotate
    # - content.tabs.link
    # - header.autohide
    # - navigation.expand
    - navigation.indexes
    # - navigation.instant
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - toc.integrate
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: purple
      accent: light blue
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
      accent: blue grey
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/logo.svg
  icon:
    logo: logo

# Plugins
plugins:
  - search
  # - redirects:
  #     redirect_maps:
  #       index.md: minecraft/index.md
  - minify:
      minify_html: true

# Customization
extra_css:
  - stylesheets/extra.css

extra:
  analytics:
    provider: google
    property: G-BYVBBZ5V97
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/unicornia
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/UnicorniaDC
    - icon: fontawesome/brands/reddit
      link: https://www.reddit.com/r/UnicorniaCommunity

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:materialx.emoji.to_svg
      emoji_index: !!python/name:materialx.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Page tree
nav:
  - Main Site: "https://unicornia.net"
  - Home: index.md
  - Minecraft:
    - minecraft/index.md
    - Features and Plugins: minecraft/features-plugins.md
    - New Player Guide: minecraft/new-player-guide.md
    - How to Claim Land: minecraft/how-to-claim-land.md
    - SlimeFun Guide: minecraft/slimefun.md
    - mcMMO Guide: minecraft/mcmmo-guide.md
    - Custom Enchantments and Items: minecraft/custom-enchants-and-items.md
    - Jobs Guide: minecraft/jobs-guide.md
    - MyPet Guide: minecraft/pets-guide.md
    - Pet Skill Trees: minecraft/pet-skill-trees.md
    - Flight Systems: minecraft/flight-systems.md
    - AutoShulkers: minecraft/autoshulker.md
    - VIP: minecraft/vip.md
    - Rewards: minecraft/rewards.md
    - All Commands: minecraft/commands.md
    - Drop Tables: minecraft/droptables.md
  - Discord:
    - discord/index.md
    - How to Use Discord: discord/how-to-use-discord.md
    - How to Spoiler Images: discord/how-to-spoiler-images-on-discord.md
    - How to Upload Emojis to a Server: discord/how-to-upload-emojis-to-a-discord-server.md
    - How to Hide Channels: discord/how-can-i-hide-channels.md
    - How to Mute a Channel: discord/how-can-i-mute-a-channel.md
    - How to Mute a Server: discord/how-do-i-mute-a-discord-server.md
    - How to Change Nickname: discord/how-to-change-nickname-discord.md
    - How to Block Someone: discord/how-do-i-block-someone-on-discord.md
    - How to Go Offline: discord/how-do-i-go-offline-on-discord.md
    - How to Change ID Number: discord/how-do-i-change-my-id-number-in-discord.md
    - How to Get IDs: discord/how-to-get-ids-on-discord.md
    - How to Show What You Are Playing/Listening: discord/how-do-i-share-what-im-playing-or-listening-to-on-discord.md
    - How to Setup 2-Factor Authentication: discord/how-do-i-set-up-two-factor-authentication-on-discord.md
    - Are Deleted Messages Actually Deleted?: discord/are-deleted-discord-messages-actually-deleted.md
    - Are Bots Safe?: discord/are-bots-in-discord-safe.md
    - Is My IP Address Safe?: discord/is-my-ip-address-safe-while-using-discord.md
    - Discord Shortcuts: discord/are-there-keyboard-shortcuts-in-discord.md